#this script reads the sentiment scores from the CSV file generated by compare_title_vs_chunked_selftext_senti.py, calculates daily and weekly averages, and plots the results.
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


# --------------------------------------------------
# 1. File paths
# --------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
INPUT_FILE = SCRIPT_DIR.parent / "reddit_title_vs_chunked_selftext_sentiment_test.csv"
DAILY_OUTPUT = SCRIPT_DIR / "daily_title_vs_chunked_sentiment.csv"
WEEKLY_OUTPUT = SCRIPT_DIR / "weekly_title_vs_chunked_sentiment.csv"
PLOT_OUTPUT = SCRIPT_DIR / "daily_weekly_title_vs_chunked_sentiment.png"

SCORE_COLUMNS = [
    "title_sentiment_score",
    "chunked_sentiment_score",
]


# --------------------------------------------------
# 2. Load and validate the sentiment results
# --------------------------------------------------

df = pd.read_csv(INPUT_FILE)

required_columns = {"date", *SCORE_COLUMNS}
missing_columns = required_columns.difference(df.columns)

if missing_columns:
    raise ValueError(
        "The input file is missing required columns: "
        + ", ".join(sorted(missing_columns))
    )

df["date"] = pd.to_datetime(df["date"], errors="coerce")

for column in SCORE_COLUMNS:
    df[column] = pd.to_numeric(df[column], errors="coerce")

df = df.dropna(subset=["date"])

if df.empty:
    raise ValueError("No rows with valid dates were found in the input file.")


# --------------------------------------------------
# 3. Calculate daily and weekly average sentiment
# --------------------------------------------------

daily = (
    df.groupby(df["date"].dt.normalize())[SCORE_COLUMNS]
    .mean()
    .reset_index()
    .sort_values("date")
)

# W-SUN creates calendar weeks ending on Sunday.
weekly = (
    df.set_index("date")[SCORE_COLUMNS]
    .resample("W-SUN")
    .mean()
    .dropna(how="all")
    .reset_index()
    .sort_values("date")
)

daily.to_csv(DAILY_OUTPUT, index=False)
weekly.to_csv(WEEKLY_OUTPUT, index=False)


# --------------------------------------------------
# 4. Plot the daily and weekly averages
# --------------------------------------------------

fig, axes = plt.subplots(2, 1, figsize=(13, 9))

plot_settings = [
    (axes[0], daily, "Daily average sentiment"),
    (axes[1], weekly, "Weekly average sentiment"),
]

for axis, data, title in plot_settings:
    axis.plot(
        data["date"],
        data["title_sentiment_score"],
        label="Title only",
        linewidth=1.8,
    )
    axis.plot(
        data["date"],
        data["chunked_sentiment_score"],
        label="Title + selftext",
        linewidth=1.8,
    )
    axis.axhline(0, color="black", linewidth=0.8, alpha=0.6)
    axis.set_title(title)
    axis.set_ylabel("Mean sentiment score")
    axis.grid(alpha=0.25)
    axis.legend()

axes[1].set_xlabel("Date")
fig.suptitle("FinBERT sentiment: title versus title + selftext", fontsize=15)
fig.autofmt_xdate()
fig.tight_layout()
fig.savefig(PLOT_OUTPUT, dpi=300, bbox_inches="tight")
plt.show()

print(f"Saved daily averages: {DAILY_OUTPUT}")
print(f"Saved weekly averages: {WEEKLY_OUTPUT}")
print(f"Saved plot: {PLOT_OUTPUT}")
